services:
  - postgresql
before_script:
  - psql -c 'create database coherence_test;' -U postgres
language: elixir
elixir:
  - 1.7
otp_release:
  - 20.0
sudo: false
notification:
  recipients:
    - smpallen99@yahoo.com
